server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name english.tlpy8.com 47.120.46.32;
    include /etc/nginx/snippets/english-again-static.conf;
    access_log /var/log/nginx/english-again.access.log;
    error_log /var/log/nginx/english-again.error.log;
}
